### ISSUE TITLE
已启用正版验证的服务器，大小写不同导致可移除他人白名单

### ISSUE THREAD

**Issue by ChinoKou** [Minecraft-QQBot/BotServer#14]
假如群内qq 123 的mc正版id为ABC，此时他在群内使用/bound abc获取了白名单
因为启用了正版验证的mc服务器中whitelist命令会自动校验大小写，此时mc服务器控制台会输出已添加白名单ABC
倘若群内qq 456 的这个人使用/bound aBc获取了白名单，再使用/bound remove
此时服务器会将ABC这个id移出白名单

**Comment by Lonely-Sails** [comment]
此问题已解决，由于判断玩家名称是否已被绑定时没有考虑玩家名称的大小写。预计 v2.0.2 发布。
