### ISSUE TITLE
希望增加satori适配器

### ISSUE THREAD

**Issue by Fox-ace** [Minecraft-QQBot/BotServer#21]
现在satori api已经够了，koishi也能连接onebot，为什么不能直接走satori还需要单独在onebot里添加一个ws反向？我试了一下直接在代码里换适配器，会报错

**Comment by Fox-ace** [comment]
刚刚试了一下，2个ws反向会导致其中的一个失效，所以对于koishi/其他使用onebot的框架，这是影响用户体验的，而对于koishi/satori框架，这是一个解决方案

**Comment by Fox-ace** [comment]
我去把仓库fork了，我也研究一下，如果可以的话会提交pr

**Comment by Lonely-Sails** [comment]
此项目基于Nonebot和Koishi有什么关系？

**Comment by Lonely-Sails** [comment]
对于 Satori 的支持将会在 v3 同 Kook 等一同加入。
