### ISSUE TITLE
Enhance Compatibility for Pure Bukkit/Pure Hybrid Servers

### ISSUE THREAD

**Issue by Zhou-Shilin** [Minecraft-QQBot/BotServer#4]
**Title: Enhance Compatibility for Pure Bukkit/Pure Hybrid Servers**

**Issue Description:**

Hello,

Firstly, thank you for developing and maintaining this fantastic Minecraft QQBot. It has been incredibly useful for integrating Minecraft with QQ using the MCDR plugin.

**Problem:**
Currently, the bot only communicates with Minecraft through the MCDR plugin, which works well but has limitations, especially on pure Bukkit or Hybrid servers. Users have reported some issues when using the bot on these types of servers, primarily due to compatibility problems.

**Suggestion:**
To improve compatibility and support for pure Bukkit and Hybrid servers, I suggest adding a feature that allows the bot to:
1. **Read Server Log Files**: Use the log files to capture and interpret in-game messages and events.
2. **Send Messages via RCON**: Use the RCON protocol to send `tellraw` commands to the Minecraft server, which can display messages in-game.

**Benefits:**
- This approach would provide a more universal method for communication, reducing dependency on the MCDR plugin.
- It would enable the bot to work seamlessly on different server setups, including pure Bukkit and Hybrid servers, thereby avoiding the issues users face on these platforms.

**Implementation Ideas:**
1. **Log File Reader**: Develop a log file reader module to monitor the Minecraft server's log file for specific events and messages.
2. **RCON Integration**: Use the existing RCON protocol to send `tellraw` commands to the Minecraft server, which can then be used to display messages.

**Example:**
- **Log File Parsing**: Monitor the server log file for chat messages, player joins, and leaves, etc.
- **RCON Command**: Send a `tellraw` command via RCON to display a message in the Minecraft server.

```python
import re
import rcon

# Example: Read log file and capture messages
log_file_path = '/path/to/minecraft/server/logs/latest.log'
message_pattern = re.compile(r'^\[\d{2}:\d{2}:\d{2}\] \[Server thread/INFO\]: <([^>]+)> (.+)$')

with open(log_file_path, 'r') as log_file:
    for line in log_file:
        match = message_pattern.match(line)
        if match:
            player, message = match.groups()
            print(f'{player}: {message}')

# Example: Send a message via RCON
rcon_client = rcon.Client('localhost', port=25575, password='your_rcon_password')
rcon_client.command('tellraw @a {"text":"Hello, Minecraft!"}')
```
**Conclusion:**
Adding this functionality would greatly enhance the bot's compatibility and usability across different Minecraft server types. This change would benefit many users who run pure Bukkit or Hybrid servers and wish to integrate your bot seamlessly.

Thank you for considering this suggestion. I am happy to help test or provide further feedback if needed.

Best regards,
BaimoQilin (@CubeGPT)

**Comment by Lonely-Sails** [comment]
详见 [Bukkit](https://www.github.com/Minecraft-QQBot/Bukkit) 插件
